### ISSUE TITLE
Confirmed? GetLootSlotInfo can return nil quality

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#108]
It appears that GetLootSlotInfo may return nil quality some time. I'm not sure how to deal with it. Terminate the LootOpened when this happens, or delay by 1s then rerun the function?

The line number of the following is from the current master commit:  ca5a9e6
```
1x RCLootCouncil\ml_core.lua:1299: attempt to compare number with nil
RCLootCouncil\ml_core.lua:1299: in function `ShouldAutoAward'
RCLootCouncil\ml_core.lua:779: in function `LootOpened'
RCLootCouncil\ml_core.lua:747: in function `OnLootOpen'
RCLootCouncil\core.lua:1726: in function `?'
...ACU\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ACU\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...ACU\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...xternal\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil
```

**Comment by SafeteeWoW** [comment]
Large update often has some errors. I will continue to monitor errors duing this week's raid.

**Comment by evil-morfar** [comment]
Odd, that has never been an issue before.

**Comment by SafeteeWoW** [comment]
There was some strange issues today, some may caused by bugs in RC-EPGP, which I fixed just now. I will double check if there is any errors.

**Comment by SafeteeWoW** [comment]
Happened again today when looting trash.
```
1x RCLootCouncil\ml_core.lua:1299: attempt to compare number with nil
RCLootCouncil\ml_core.lua:1299: in function `ShouldAutoAward'
RCLootCouncil\ml_core.lua:779: in function `LootOpened'
RCLootCouncil\ml_core.lua:747: in function `OnLootOpen'
RCLootCouncil\core.lua:1730: in function `?'
```

**Comment by SafeteeWoW** [comment]
Probably should add a debug log statement to track what exactly GetLootSlotInfo returns.

**Comment by SafeteeWoW** [comment]
Happen again when I loot heroic Aggramar, and this bug causes extra items shown up in session window. (First loot open does not show session frame due to this bug, however added some items into the session, the 2nd click opens the session frame, however there are extra items

**Comment by SafeteeWoW** [comment]
Saved variable:
https://gist.github.com/SafeteeWoW/12c27729a4cbf1618aeb1c446afd5b19

**Comment by SafeteeWoW** [comment]
In conclusion, the item in loot window is probably no longer cached.

**Comment by SafeteeWoW** [comment]
The Blizzard code of loot frame does have a piece of code to handle this when LootSlotHasItem(slot) is true, but GetLootSlotInfo is not. It simply rerun the update after 1s.

**Comment by SafeteeWoW** [comment]
See PR #114

**Comment by SafeteeWoW** [comment]
See PR. close this for now
