### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by victaxel** [evil-morfar/RCLootCouncil2#109]
Hi, I am planning a web app for presenting data from rclootcouncil exports. Is this available somewhere? I am unfortunately unable to generate this myself.

**Comment by SafeteeWoW** [comment]
I am not sure what you mean. Isn't data available by exporting it?

**Comment by victaxel** [comment]
I don't play WoW and have a hard time getting a hold of a csv to test with. I was however lucky and able to get my hands on a csv just a few minutes ago. Thanks anyway.

**Comment by evil-morfar** [comment]
You might be better off using the saved variables file directly, so people don't have to do exports - although there's a chance that data structure may change in the future, whereas exports most likely only will have additions.

Do let us know what you come up with :)
