### ISSUE TITLE
version check nil error

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#112]
3x RCLootCouncil\Libs\lib-st\Core.lua:587: attempt to index local 'rowdata' (a nil value)
RCLootCouncil\Libs\lib-st\Core.lua:587: in function `GetCell'
RCLootCouncil\Libs\lib-st\Core.lua:660: in function `OnLeave'
RCLootCouncil\Modules\versionCheck.lua:180: in function <RCLootCouncil\Modules\versionCheck.lua:178>

**Comment by evil-morfar** [comment]
I have no idea how you managed to do that.
