### ISSUE TITLE
Version check claims v 2.1.10 is older than 2.1.8

### ISSUE THREAD

**Issue by AlexejK** [evil-morfar/RCLootCouncil2#12]
Upon login getting warning that my version 2.1.10 is out of date, and that the latest version is 2.1.8.

**Comment by Xetoxyc** [comment]
Same for everyone i think 
just see core.lua ln:675

there is just a simple string compare  ;)

8 ist just bigger then 1

**Comment by AlexejK** [comment]
Yepp, saw that :) I personally would suggest SemVer implementation to be included as this will cover most use-cases and not need to do additional stuff for parsing and comparing.

Something like https://github.com/kikito/semver.lua

**Comment by evil-morfar** [comment]
Thanks for the report - it's really one of those stupid mistakes that only shows up on special occasions, this time with the patch version reaching 10. 

Also, I'm already using SemVer - it's just the comparison between clients that fails as it's currently formatted as a string.

**Comment by AlexejK** [comment]
Cool 👍 

I saw the versioning of the addon following the SemVer standard, but my point was mainly for SemVer library to be used whenever dealing with version logic in the code to avoid the need of parsing those string versions etc.

**Comment by evil-morfar** [comment]
I see - it's however a bit overkill for what's needed in this project :)
