### ISSUE TITLE
Idea: Option to Always show tooltip

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#123]
We always need to check the tooltip of the item. Why not always show it?
An awful PS as an example for votingFrame. Should also do it on the loot frame.
![untitled](https://user-images.githubusercontent.com/30888549/33525130-10b131d6-d7de-11e7-973f-f2a72ebca6ce.png)

**Comment by SafeteeWoW** [comment]
My idea is to show an arrow on the left of item icon to toggle tooltip on/off

**Comment by evil-morfar** [comment]
I see what you're getting at, but I don't think it's really needed. I would expect people to have suggested this if they really wanted it, but all I've heard is people concerned about the width of the voting frame.

My biggest issue with this is the arrow button - but it could honestly just be built into the item icon (i.e. press the icon to get a tooltip).

This has such a low impact that I don't really care, but I personally wouldn't use it.

**Comment by evil-morfar** [comment]
#126 #127
