### ISSUE TITLE
Loot roll selection button width

### ISSUE THREAD

**Issue by AlexejK** [evil-morfar/RCLootCouncil2#13]
This is a minor one, mostly UI improvement if nothing else, but annoying for someone with an OCD like me :).

When you have buttons configured with labels like: "BiS", "Tier/WF", "Main", "OS", "Transmog" the sizes of buttons are very different. This does make sense to the extend that labels are different in width, but it's very disturbing when ML configured it like above and I have also made window size smaller (as its just oversized for me right now).

Suggestion: maybe there should be a minimal reasonable width for buttons that matches 4-5 character width of the label? This would make "BiS", "OS", and "Main" buttons have same width, with others being a bit wider.

**Comment by evil-morfar** [comment]
Sounds reasonable.
