### ISSUE TITLE
Cant click Pass Button on Loot frame

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#130]
1x RCLootCouncil\core.lua:2620: attempt to index field '?' (a nil value)
RCLootCouncil\core.lua:2620: in function `GetButtonText'
RCLootCouncil\Modules\lootFrame.lua:141: in function `OnRoll'
RCLootCouncil\Modules\lootFrame.lua:271: in function <RCLootCouncil\Modules\lootFrame.lua:271>

**Comment by evil-morfar** [comment]
Assuming you're using the first 2.7.2 release and didn't change something, this shouldn't be possible. Otherwise SV is required.

**Comment by evil-morfar** [comment]
Incedently someone else posted an seemingly identical error - codewise I still can't see an potential error, but I am investigating.

**Comment by SafeteeWoW** [comment]
It's very simple mistake actually

**Comment by SafeteeWoW** [comment]
72c888da17 is bugged

**Comment by evil-morfar** [comment]
Yup, just discovered it aswell.
