### ISSUE TITLE
Some people cant see the loot frame.

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#131]
Just let you know. Happens randomly to random people

**Comment by SafeteeWoW** [comment]
I am in raid. cant provide detail atm

**Comment by evil-morfar** [comment]
Anyway related to the recent changes? I'm just about to push an hotfix to the pass button stuff - would appreciate more feedback when possible.

**Comment by SafeteeWoW** [comment]
Several people are more likely to be affected by it.

**Comment by SafeteeWoW** [comment]
I'll provide feedback after each boss

**Comment by SafeteeWoW** [comment]
Only several people are affected. Their version is 2.7.1 or 2.7.2.
We can see loot frame some times, sometimes cant

**Comment by SafeteeWoW** [comment]
I am unlikely to provide any SV until raid ends in 2h.

**Comment by SafeteeWoW** [comment]
Not sure if it is a Blizzard bug. Everytime I start a session. Those player receives system message "cannot find player "Unknown-Servername"

**Comment by evil-morfar** [comment]
That points to any check of the ML/name - I just don't see any changes to that in the last two updates.

**Comment by SafeteeWoW** [comment]
Probably we should check if the ML name is _G.UNKNOWNOBJECT

**Comment by evil-morfar** [comment]
The check in `NewMLCheck` should probably check for the global string - but even then, the ML name should have been gathered before it's used.

**Comment by evil-morfar** [comment]
Are you playing with english locale? If not, is it "Unknown" or is it translated? (I never thought about the latter).

**Comment by SafeteeWoW** [comment]
I am, but my raiders use enUS, zhCN, zhTW.

**Comment by evil-morfar** [comment]
So "Unknown" or translated? Need to know if I can include _G.UNKNOWNOBJECT instead.

**Comment by SafeteeWoW** [comment]
Their system chat message shows "未知目标”, which should be _G.UNKNOWNOBJECT

**Comment by SafeteeWoW** [comment]
Ok, I think this is the problem because I can solve the issue by switching ML and then switching back.

**Comment by SafeteeWoW** [comment]
Let's include both "Unknown" and _G.UNKNOWNOBJECT

**Comment by evil-morfar** [comment]
I'm wondering why this hasn't happened before though.. Pushing a new version now.

**Comment by evil-morfar** [comment]
Good point. It's too late at night for me 💤

**Comment by SafeteeWoW** [comment]
Blizzard code confirms "Unknown" is localized.
```
-- FrameXML/RaidUI.lua:746
local unitName = UnitName(unit);
if ( unitName and unitName ~= UNKNOWNOBJECT ) then
```

**Comment by evil-morfar** [comment]
Because the name also contains realmname, i.e. "Unknown-Realm".
