### ISSUE TITLE
Stop using Curseforge issue tracker.

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#132]
Curseforge issue tracker is bad and cant even solve a simple problem that file cant ends with .lua
Can you switch to Github issue tracker? There is a setting in Curseforge to change it. And copy and paste the comments of current open issues. And howto make issue template: https://github.com/blog/2111-issue-and-pull-request-templates

---
Tired of asking saved variables and teach people how to upload saved variabes.
We should make a feature to generate serialized form (probably not AceSerializer ) of saved variable and allow people copy and paste them in-game. This is easier.

---
It sucks to have so many places to talk about addon issues
1. www.curseforge.com
2. wow.curseforge.com
3. https://wow.curseforge.com/projects/rclootcouncil/issues
4. github

**Comment by evil-morfar** [comment]
I agree curseforge sucks, but at least it's somewhat familiar to most people. The average user also doesn't have a GitHub account, and forcing them to make one just to post a ticket is not to be recommended. I could however include a link to GitHub issues in the addon description.
---

Easier yes, but such a large pasted string would make a mess of a report without spoiler tags.

---
I don't really think so. First of all it's really only 3 places. I agree it's a bit inconvenient when the same thing is discussed all 3 places, but I do like having a division between the consumer and developer side of things.

**Comment by SafeteeWoW** [comment]
> Easier yes, but such a large pasted string would make a mess of a report without spoiler tags.

Still much better than no Saved Variable. I think it's fine as long as the issue report tutorial is easy to understand.
