### ISSUE TITLE
Show socket/leech, avoidance, etc with ilvl

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#139]
I want to show socket/leech, avoidance, etc with ilvl.

The display is like
```930/socket```
```930/leech```

But in the current design, additional information need to be transmitted for the ML. I don't like it.

**Comment by evil-morfar** [comment]
There's no real reason to transmit it from the ML, as we found out getting iteminfo is pretty quick. Feel free to implement it locally.

**Comment by evil-morfar** [comment]
See #144
