### ISSUE TITLE
Show Item Secondary Stats

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#147]
Can you show the secondary stats (Critical/Mastery/Versatility/Haste) of the item in white text (These stats is colored in white in tooltip, so I recommend to color them in white text) in votingframe and the lootframe? The value doesn't need to be shown. This could be very convenient.

Some adjustment to other widget is needed.

Sample display is
```Critical/Mastery``` (The stat with higher value is shown first, more crit than mastery)
```Mastery/Critical``` (More mastery than crit)

WoW API for this feature:
1.  ```GetItemStats``` (Item needs to be cached)

Constants:
1. ```ITEM_MOD_HASTE_RATING_SHORT```
2. ```ITEM_MOD_MASTERY_RATING_SHORT```
3. ```ITEM_MOD_CRIT_RATING_SHORT```
4. ```ITEM_MOD_VERSATILITY```
These constants is the key of the table returned by GetItemStats.
Its localized text can be fetched from , for example,  _G["ITEM_MOD_HASTE_RATING_SHORT"]

Not a difficult feature to implement, the issue is just how to properly adjust the display.

**Comment by evil-morfar** [comment]
Indeed - and exactly how to show them is a very huge issue. I'll see if I can figure something out.

**Comment by SafeteeWoW** [comment]
Dont forget to consider the case when there are more than 2 stats on the item. Currently it only occurs on the legendary items, but for completeness and for the future, do consider that.

**Comment by evil-morfar** [comment]
I've tried a few different things, none of which I liked. My best result was with putting it over the item icon (ignore the "out of bounds" text, this was just the only picture I saved):
![image](https://user-images.githubusercontent.com/10189576/37909949-99ba7988-310c-11e8-8a18-cacbb324ac48.png)

I'm not sure how useful this really is anyway..

**Comment by evil-morfar** [comment]
Haven't found a good way to do this. I'm also not sure how usable this is anyway. Closing.
