### ISSUE TITLE
Chat command changes

### ISSUE THREAD

**Issue by evil-morfar** [evil-morfar/RCLootCouncil2#148]
I've been postponing this for a while, but finally got around to do it. I might as well do it properly while I'm at it, so here's a short heads up for v2.7.6:

I wanted to enhance the formatting of the output by colorizing the command, hence a need to change to current structure. I created a new function (`RCLootCouncil:ModuleChatCmd()`) so it doesn't overlap with the old format, which is still supported.

Here's the implementation from GroupGear to make the switch whenever the user upgrades:
```lua
if addon:VersionCompare(addon.version, "2.7.6") then
   addon:CustomChatCmd(self, "Show", "- gg - Show the GroupGear window (alt. 'groupgear' or 'gear')", "gg", "groupgear", "gear")
else
   addon:ModuleChatCmd(self, "Show", nil, "Show the GroupGear window (alt. 'groupgear' or 'gear')", "gg", "groupgear", "gear")
end
```

**Comment by SafeteeWoW** [comment]
I will go and update EPGP module when 2.7.6 is close to ready.
Progressing on Mythic Argus and want to kill him before Lunar Festival, so not going to write big changes.

**Comment by SafeteeWoW** [comment]
Uploaded RCLootCouncil-EPGP v2.2.3 to fix this.
