### ISSUE TITLE
Send if appearance is collected.

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#149]
This is probably for v2.9.
1. As a ML, I want to see if a raid member has collected an appearance so I can easily distribute an item that  everyone has passed.
2. The only technical issue is that how I can know if the appearance is collected when the item is a set token. There is no API to relate the tier token to the appearance. Some data is needed in the LUA file, but it is hard to export this data without lots of manual work.
3. For non-token, such info can be easily retrieved by tooltip parsing.

**Comment by evil-morfar** [comment]
I image `C_Transmog` and `C_TransmogCollection` can be helpful. `C_TransmogCollection.IsNewAppearance` sounds promising.

In ExtraUtilities, I always wanted to know how many set pieces a candidate has equipped, but I haven't found a way to do it without hardcoding data. For appearances, the above will probably work though.

I'm reluctant to include this in RCLootCouncil. To me, this sounds like a niche thing, which I've purposely pushed to EU, where it definitely could go. I also once considered doing a "Gear Manager" module, which would track gear the players are wearing, and register how they got the gear (which response, other places, etc) along with other statistics. If that was ever made, then this idea would fit nicely in there as well.

**Comment by SafeteeWoW** [comment]
The problem to include it in EU is that ML would need raid members to also install EU to acquire the appearance information, and I think in the current EU, you are not requiring raiders to install EU?

**Comment by SafeteeWoW** [comment]
I know C_Transmog and C_TransmogCollection, but those API uses appearance set id, which is not the same as the set id returned by GetItemInfo, which is not returned any way if the item is a set token, not an actual gear.

Another problem is that one set token is associate with the appearances of 4 classes, and token with different difficulty offers different appearances. If we do a hard coding, it's a lot of work.

**Comment by evil-morfar** [comment]
There's a few things in EU that doesn't require others to install it, but most of the new columns does. It's relatively simple for a guild to require people to install several addons if they so desire.

After a bit of research, I don't think there's anyway to gather this info for set tokens without hardcoding the data.

**Comment by SafeteeWoW** [comment]
See PR #154
