### ISSUE TITLE
Plan if Master Loot is Gone in BFA

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#157]
According to the [developer liveblog on March 15](http://www.wowhead.com/news=282736/liveblog-of-the-march-15-battle-for-azeroth-alpha-q-a-with-ion-hazzikostas), the Game Director Ion Hazzikostas talks about the possibility of the retirement of Master Loot

> Will personal loot be the only option for current-level raids?
> 
> It's a reasonable expectation. There's a higher total loot count on personal, and the reason that people currently doing Master Loot is for tier sets which don't exist in BFA. 

Though it's definitely not a final decision, as eliminating the option to Master Loot has lots of side effects, I think more work should be done towards the personal loot.
I think the essential features to make the addon work properly in the personal loot.
1.  Automatic RC session popup when corpse is looted by raiders in personal loot mode.
2. Loot history should record the origin owner of the item, and should update automatically when traded (Even if trade to someone who is not the winner in a RCLootCouncil session)
3. A trade frame to show the information who should be traded and what item should be traded, an easy button to initiate the trade if people are close enough, etc.

**Comment by evil-morfar** [comment]
I saw that yesterday as well and it did get me worried. I don't believe they'll really remove ML (although they have been pushing for it for some time).

If they really do remove it, then I fear the majority of guilds currently using RCLootCouncil won't bother with it in the future.

As for your points:
1. Yes, but only if the item is tradable (assuming it will follow the current PL rules).
2. Origin yes - not sure it's worth waiting for the item to be traded, as that would, worst case, require monitoring the item potentially for days (an item is still tradable within 2 hours of game time, even if you log out). Just recording the award (as now) should be good enough. It's not a bad idea though.
3. Agreed. 

And:
4. If a corpse loot is still required, then the sessions would need to be dynamic so items can be added to an ongoing session whenever the stragglers gets ressed and/or decides to loot. 

Even if they don't remove ML, these points should still be incorporated with a BFA release.
