### ISSUE TITLE
RCLootCouncil Discord Server

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#159]
I am asking if you have interest to create a RCLootCouncil Discord Server.
My Discord ID is ```Safety#1191```

The server can make the following discussion more convenient and be involved by more people
1. New Feature Announcement
2. Bug Report
3. Feature Suggestion
4. We can discuss implementation detail with more people.
5. Loot Distribution Rule Discussion (Loot Council, DKP, EPGP)

If you are interested, please create the server and add the server link to Curseforge and the addon. I think similar to DBM and BigWigs, RCLootCouncil is a popular addon and deserve a discord server. Thanks.

**Comment by evil-morfar** [comment]
I'm not so sure about making it too public, as that would add yet another place to check for bug reports/comments etc. It could be useful for communicating with select people though.

**Comment by evil-morfar** [comment]
https://discord.gg/HewaUWd

**Comment by SafeteeWoW** [comment]
I have joined the server. Can you promote me?
