### ISSUE TITLE
Lua Performance Optimization and New Serializer and Compressor

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#168]
Before next expansion, I will release two standalone libraries. One serializer and one compressor, which generates significantly smaller data than the currently commonly used AceSerializer and LibCompress.

---
1. The planned name of those libraries:
    1. RCSerializer
          Not sure. Should I call this RC? Less readable than AceSerializer, but produce much smaller data by  string reuse and several other small improvements. I was planning to implement a special optimization targeting item string, but it's not very needed with the help of a compressor, and it's not good for an general library.
   2. LibDeflate
        (Or call this RCCompressor? )A compressor uses DEFLATE algorithm. (See RFC1951). A litle bit slower, but provides much smaller data, especially if there are lots of redundancies.

2. The perfomance of LibDeflate
   1. The overhead of LibDeflate is of course bigger than LibCompress. So small data suitable within one WoW message (255 bytes) including header will not be compressed, to save CPU time. (Storing 5 extra bytes as header, without actual compressing, still following DEFLATE spec)
   2. This library is unfinished. I haven't implement decompressor. The correctness of compressor part is checked by the help of an external decompressor.

[smalltest.txt](https://github.com/evil-morfar/RCLootCouncil2/files/1895504/smalltest.txt)
This a reconnect data serialized by RCSerializer. The original size is 28459 bytes.

LibCompress: 37ms, 18595 bytes, 65.3% of original
LibDeflate: 73ms, 10872 bytes. 38% of original, 57% of LibCompress.
gzip -1: 40ms(including loading and IO time, so not that useful), 7539 bytes
gzip -1: 44ms(including loading and IO time, so not that useful), 5873 bytes.

There are still lots of room to improve compression ratio and speed.

3. The performance of RCSerialzer was mentioned in #116, and I have another good idea to reduce the serialized size of nested table.

   {{link=A, bagged=B}, {link=C, bagged=D}} will be serialized similar to  { link, bagged, {A, B}, {C, D}}
---
1. Suggestion to the name of those libraries? (Haven't pushed the code. It's too unfinished.)
2. Opinion to the performance.
3. Can you provide any more test data?

---
If you have time, can you help to compare the performance of the following IN-GAME?
All of the following needs to be executed many times to make a difference, but there is difference
1. bit.rshift(x, 8) **VS** (x-x%256)/256  (Dont forget to localize bit.rshift)
2. bit.lshift(x, 8) **VS** x*256 (Don't forget to localize bit.lshift)
3. bit.band(x, 255) **VS** x%256 (Don't forget to localize bit.band)
3. table.insert(t, x) **VS** t[#t+1]=x. Dont forget to localize table.insert
My current observation is that the performance of function is always worse than its non-function equivalence.
5. string.char(x) **vs** byteToCharTable(x), where byteToCharTable is a pre-generated table such that byteToCharTable[i] == string.char(i), for i=0..255, Dont forget to localize string.char

**Comment by SafeteeWoW** [comment]
a good wiki page for lua performance tips
https://springrts.com/wiki/Lua_Performance

**Comment by SafeteeWoW** [comment]
https://github.com/SafeteeWoW/LibDeflate
Only compression has been implemented and it's unfinished.
I have improved the performance to 41ms (better than LibCompress).

**Comment by SafeteeWoW** [comment]
I am close to finish the compressor side of the LibDeflate, and has made significant improvement.
Still Use the above file as the example https://github.com/evil-morfar/RCLootCouncil2/files/1895504/smalltest.txt

Unlike LibCompress, LibDeflate does not guarantee there is no NULL character in the compressed data if there is no NULL in the input. However, NULL in the compressed data is very rare, no more than 1%, so I am not considering the impact that I need to use extra space to encode NULL characters

The original size of the file is 28459 bytes.
LibCompress reduces this to 18595 bytes (1.53 ratio), it takes 40ms

For LibDeflate:
1. To achieve ratio similar to gzip -1 (7625 bytes, 3.73 ratio, 60% smaller than LibCompress), it takes 40ms, as fast as LibCompress
2.  To achieve ratio similar to gzip -2 (7185 bytes, 3.96 ratio, 63% smaller than LibCompress), it takes 58ms
3. To achieve ratio similar to gzip -3 (6729 bytes, 4.23 ratio), it takes 100ms
4. To achieve ratio similar to gzip -4 (6220 bytes, 4.57 ratio), it takes 450ms
5. gzip - 9 would make this file < 6000bytes, but I haven't implement that compression setting.

**Comment by SafeteeWoW** [comment]
Another example is https://gist.github.com/evil-morfar/b1ee4aadc17ba07024df2014b2d46194 mentioned in #125

The original size is 68831 bytes.
LibCompress reduces this to 33955 bytes in 90ms

Comparing this to LibDeflate in different compression settings.
1 . 10189 bytes in 90ms
2.  9132 bytes in 94ms
3.  8276 bytes in 122ms

It is significant improvement considering WoW only has 1KB/s addon channel bandwidth.

-----
Now consider a more realistic example.
The following table contains all item strings equipped by a player, plus some additional meta data.
Encoded data by current RCSerializer:  [itemStrings.txt](https://github.com/evil-morfar/RCLootCouncil2/files/1911557/itemStrings.txt)
```
local t = {
	p=true,
	ilvl=987.65,
	g= {
	"147013:5890:::::::110:105::6:3:3563:1517:3336",
	"134497:5890:151584::::::110:105::35:4:3418:1808:1587:3337",
	"137535:5890:::::::110:105::16:3:3418:1567:3528",
	"147014:5437:::::::110:105::5:3:3562:1517:3337",
	"142207:5439:::::::110:105::35:3:3418:1562:3337",
	"152020::::::::110:105::3:3:3610:1472:3528",
	"147040::::::::110:105::6:3:3563:1517:3336",
	"152021::::::::110:105::5:3:3611:1487:3528",
	"137361::::::::110:105::35:4:3418:42:1587:3337",
	"151986::::::::110:105::5:3:3611:1487:3528",
	"132366::::::::110:105:::3:3529:3459:3570",
	"147039::::::::110:105::3:3:3561:1512:3337",
	"137361::151585::::::110:105::35:4:3418:1808:1597:3337",
	"132366::::::::110:105:::3:3529:3459:3570",
	"147039::::::::110:105::6:3:3563:1522:3336",
	"132864::::::::110:105:::2:1811:3630",
	"152006::::::::110:105::5:3:3611:1487:3528", },
}
```

The origin size is 738 bytes.
LibCompress reduces this to 366 bytes in 1.46ms

Comparing this to LibDeflate in different compression settings.
1. 264 bytes in 1.9ms
2. 253 bytes in 2.0ms
3. 250 bytes in 2.0ms
---
Do you think it's worthwhile to transmit all equipped gear if it doesn't cost much bandwidth (Fix within one SendAddonMessage API)?
I think this is useful information for people. I am implementing compression settings with higher compression ratio.

**Comment by SafeteeWoW** [comment]
The compression part is now functional.
Can you try the performance in-game with different compression level (1-9)?
There is only 1 file in this library "LibDeflate.lua" and currently one API ```LibDeflate:Compress(str, level)```

**Comment by SafeteeWoW** [comment]
https://github.com/SafeteeWoW/LibDeflate
In RCv3, I want to have the following workflow. A good habit for programmers.

1. In ```.git/hooks/pre_commit```, store the following script
```
#!/bin/sh
luacheck -g -u .
```
This will do lua static analysis and linter check before all commits, ignoring all global and unused variables warnings. If any warnings or errors presented, such as trailing whitespaces, commit will fail.

What is git hooks: https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
LuaCheck download: https://github.com/mpeterv/luacheck/releases
LuaCheck documentation: http://luacheck.readthedocs.io/en/stable/cli.html#command-line-options
There exists a luacheck Atom plugin. See LuaCheck github page.

2. Unit Tests
LuaUnit is the better Unit Test Framework so far: https://github.com/bluebird75/luaunit

3. Continuous integration (Travis CI and Appveyor)
I have learned Travis CI and Appveyor in few days. They run test for every push I made. It is so convenient and fun.

**Comment by SafeteeWoW** [comment]
LibDeflate is now actually working.
There are two APIs currently.
```
LibDeflate:Compress(str, level) -- Level is a number indicating the compression level. 1 is fastest, 9 is the slowest.
LIbDeflate:Decompress(str)
```
Can you try it out?
Note that this library is still development status, and the current decompression speed is very slow, because I have just made it working and haven't apply any optimization.

**Comment by evil-morfar** [comment]
I'm sorry, I've been really stomped at work and with exams lately. I might get some time during this week. Next week I'm on vacation, and hopefully after that I'll have a few weeks with more time for RCLootCouncil.

**Comment by SafeteeWoW** [comment]
Welcome back. Help me to test out LibDeflate?
https://github.com/safeteeWow/LibDeflate
Really spend me some time to make this project. Thanks.
Actually, I haven't tested once in-game, but it is really tested very extensively out of game.
