### ISSUE TITLE
Lua Errors on logon

### ISSUE THREAD

**Issue by Dia** [evil-morfar/RCLootCouncil2#171]
Here is my FrameXML.log
8/8 16:54:48.546  Loading add-on RCLootCouncil
8/8 16:54:48.546  ** Loading table of contents Interface\AddOns\RCLootCouncil\RCLootCouncil.toc
8/8 16:54:48.546  ++ Loading file Interface\AddOns\RCLootCouncil\embeds.xml
8/8 16:54:48.546  ++ Loading file Interface\AddOns\RCLootCouncil\Libs\DropDownMenu\UIDropDownMenuTemplates.xml
8/8 16:54:48.546  Deferred XML Node object named Lib_UIDropDownMenuButtonTemplate already exists
8/8 16:54:48.546  Deferred XML Node object named Lib_UIDropDownListTemplate already exists
8/8 16:54:48.546  Deferred XML Node object named Lib_UIDropDownMenuTemplate already exists

If I search for Lib_UIDropDownMenuButtonTemplate in my addon folder I find a list of these addons

- AutoTurnIn (disabled)
- ElvUI (enabled)
- MoveAnything (enabled)
- RCLootCouncil (enabled)

**Comment by evil-morfar** [comment]
Should be fixed in v2.9.2. Thanks for your report.
