### ISSUE TITLE
Custom Buttons is not working

### ISSUE THREAD

**Issue by jjholleman** [evil-morfar/RCLootCouncil2#172]
I changed the Button options to only have Need or Greed, however it always defaults back to the standard options that includes the Minor Upgrade option, which is not what I want.

**Comment by evil-morfar** [comment]
Odd how noone have encountered this before. Either way, I just pushed a fix - thanks for letting me know. 

You can download it directly from Github (raiders doesn't need it for the fix to work) - I'm currently testing something else, so I won't publish a new release until monday to avoid multiple releases.
