### ISSUE TITLE
Mizus RaidTracker blocks RC history window

### ISSUE THREAD

**Issue by jjholleman** [evil-morfar/RCLootCouncil2#173]
Another addon called [Mizus Raidtracker](https://wow.curseforge.com/projects/mizusraidtracker) blocks RCLootCouncil from opening the history window. Typing /rc history simply does nothing, neither does clicking the "Open the Loot History" button in the addon options.  
  
There are no LUA errors for this. It only happens if RCLootCouncil and MRT are both enabled. Somehow they are interfering.  
  
I've also listed the issue on MRT's page here: https://wow.curseforge.com/projects/mizusraidtracker/issues/74

**Comment by evil-morfar** [comment]
Odd, they used behave nicely together.
At first glance I can't find anything in either addon that causes this.

**Comment by jjholleman** [comment]
Fixed by either one of the addon's updates. 
See: https://wow.curseforge.com/projects/mizusraidtracker/issues/74
