### ISSUE TITLE
Abandon RCLootCouncil-EPGP

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#175]
Hi evil_morfar,

I no longer maintain RCLootCouncil-EPGP.

I have afk from World of Warcraft for a long time.
I did play BoA for several days upon launch, then I no longer have time to play because
the busy work schedule.
I still have contact with my guild. They did mythic raid in Uldir, and stop raiding since then. Everyone has busy life now.

Glad to see you are still maintaining RCLootCouncil. Excellent Work!

I have added you as the maintainer of RCLootCouncil-EPGP.
You can take over the maintenance if you want, but you absolutely don't have to maintain it though.
I also added another person with username "Zernin" because I saw him leave a message in RCLootCouncil-EPGP page and has intention to take over the project. It was half a year ago though.

And btw, my pure Lua compressor and decompressor project "LibDeflate" works well and have been used by several large projects including WeakAuras, TotalRp3 and Plater Nameplates. You can consider to use it, if needed.

Thank you very much,
Sincerely,
safetee (Safetyy@Illidan-US, Github: @SafeteeWoW)

**Comment by evil-morfar** [comment]
Hi there,

Sad to see you gone, but I totally understand it.
I'm also quite busy, so I'm not sure if I'll get to look into it any time soon. Also last I checked, there seemed to be some compatibility issues with epgp (dkp reloaded), which I don't really want to touch.

I'm very much looking forward to using LibDeflate - I do need to ensure my comm protocol is finalized before switching (3.0 grew to be a lot bigger than first intended, and time haven't been on my side). 

See you around, and thanks for the message!
