### ISSUE TITLE
RCLootCouncil for WoW Classic

### ISSUE THREAD

**Issue by Wulfbayne** [evil-morfar/RCLootCouncil2#176]
Requesting that RCLootCouncil be updated to work for WoW Classic.

**Comment by evil-morfar** [comment]
I don't currently have beta access, nor do I plan on spending enough time on leveling to do proper testing on Classic.

However, the addon is pretty much backwards compatible with the Classic API, and all the ML stuff is still in there, so it should require very little work to make a port. On top of my head only Ace3 libraries needs to be downgraded for it to work, along with a few ML specific options that's not currently displayed.

I do plan on making a version available at launch at the latest.

**Comment by evil-morfar** [comment]
Finally have something more official: https://www.curseforge.com/wow/addons/rclootcouncil-classic/.
