### ISSUE TITLE
rchelp, localized whisper_guide

### ISSUE THREAD

**Issue by ddiava** [evil-morfar/RCLootCouncil2#177]
The french whisper_guide string is too long to be sent (350 caracters)

**Comment by evil-morfar** [comment]
I'll see what I can do.
In the mean time, please check the translation isn't unnecessary long : https://www.curseforge.com/wow/addons/rclootcouncil/localization/languages/93/phrases#10608

**Comment by ddiava** [comment]
a more appropriate and yet more literal one would be: 
[RCLootCouncil] : numéro réponse [objet1] [objet2]. Insérez le lien de votre(vos) objet(s) que l'item (numéro) remplacerait. (réponse) étant un mot clef de la liste ci-dessous. Par exemple: '1 cupidité [objet1]'
