### ISSUE TITLE
Request: Option to require note with loot choice

### ISSUE THREAD

**Issue by brentrichardjr** [evil-morfar/RCLootCouncil2#181]
Recently, my raid team has switched to requiring a note when selecting the choice for loot. With this being a new requirement, most people (including myself) forget. Could a setting be added to force the note to be added? That way, an error message or note box pops up when trying to make a choice without the note? Thanks for the consideration.

**Comment by evil-morfar** [comment]
I'll take it into consideration. Can't promise an eta at this time.

**Comment by tyrhett** [comment]
+1 on this for sure!

**Comment by evil-morfar** [comment]
Coming with v2.18.
