### ISSUE TITLE
New Feature Idea - Track unlooted items

### ISSUE THREAD

**Issue by tyrhett** [evil-morfar/RCLootCouncil2#182]
We require raiders to pass BoE's to the raid lead, then we master loot them out through RC Loot Council. We have a decent number of raiders just not looting mobs on purpose, that way in case they get a BoE, it will just be mailed to them after.

It would be hugely beneficial if RC could track that from the "Guild News" section, and have an alert, or section that would monitor, and tell you if any BoE items were looted by a player that weren't already passed out through RC. Even if that was to complicated, just track all BoE's looted in a pane or section of the addon's UI in game, and then raid leads could match it up to the ones we know were looted during raid and RC'd out already.

**Comment by evil-morfar** [comment]
I most likely won't be making something that tracks loots from the guild news. 
Providing a way to list all BoE's looted through the addon could be done though.
