### ISSUE TITLE
Error trying to view RCLootCouncil in "Interface options"

### ISSUE THREAD

**Issue by DigiR1** [evil-morfar/RCLootCouncil2#186]
Date: 2020-04-05 16:53:04
ID: 1
Error occured in: Global
Count: 1
Message: ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua line 1863:
   AceConfigRegistry-3.0:ValidateOptionsTable(): RCLootCouncil.args.settings.args.generalSettingsTab.args.frameOptions.args.chatFrameName.name: expected a string or funcref, got 'table: 00000199C6A04490'
Debug:
   [C]: ?
   ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:50:
      ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:45
   ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:210:
      ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:205
   ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:244:
      ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219
   ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:254:
      ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219
   ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:254:
      ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219
   ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:254:
      ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219
   ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:254:
      ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219
   ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:282: ValidateOptionsTable()
   ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:335: app()
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1863: Open()
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1956:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1954
   [C]: ?
   ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:72:
      ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70
   ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:290: Fire()
   ...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:20:
      ...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:19
   [C]: Show()
   ..\FrameXML\InterfaceOptionsFrame.lua:28: InterfaceOptionsList_DisplayPanel()
   ..\FrameXML\InterfaceOptionsFrame.lua:46: InterfaceOptionsListButton_OnClick()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.4.7
  AtlasLootClassicData, vv1.4.7
  AtlasLootClassicDungeonsAndRaids, vv1.4.7
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.5
  BagnonConfig, v
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterAuraTracker, v
  CastCursor, v1.6
  ClassicCodex, vv1.3.9
  CrossGambling, v8.2.5
  DBMCore, v1.13.42
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.2.1
  ExtVendorUIClassic, v1.0.4
  GatherMate2, v1.45.5
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.56
  LeatrixPlus, v1.13.56
  MikScrollingBattleText, v5.7.149
  MooidesMountMod, v1.0
  NeatMinimap, vv1.06.01
  NeatPlates, v1.13.4.3
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v2.0
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  Questie, v5.10.0 0 fd3ff918
  RCLootCouncilClassic, v0.8.0
  SexyMap, vv5-classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.2.2.11304
  TitanClassicAmmo, v1.2.2.11304
  TitanClassicBag, v1.2.2.11304
  TitanClassicClock, v1.2.2.11304
  TitanClassicGold, v1.2.2.11304
  TitanClassicLocation, v1.2.2.11304
  TitanClassicLootType, v1.2.2.11304
  TitanClassicPerformance, v1.2.2.11304
  TitanClassicRegen, v1.2.2.11304
  TitanClassicRepair, v1.2.2.11304
  TitanClassicVolume, v1.2.2.11304
  TitanClassicXP, v1.2.2.11304
  TranqRotate, v1.2.0
  WeakAuras, v2.17.0
  WeaponSwingTimer, v4.1.0
  ZPerl, v5.9.3
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=a02)

**Comment by evil-morfar** [comment]
This is caused by Cross gambling - disable it, and you should be fine.
