### ISSUE TITLE
Backport For TBC

### ISSUE THREAD

**Issue by Macumbafeh** [evil-morfar/RCLootCouncil2#188]
Hello,
Is it possible to backport it for TBC please?

Feel free to join our Addon Discord TBC 2.4.3 if you wanna talk with our team :
https://discord.gg/5qVu56M

Thanks!

**Comment by evil-morfar** [comment]
I don't really know. The current version of the addon was created in 2014-2015, so some of the code might be old enough to have been present in tbc, but others are definitely never.

One thing's for sure: I won't be doing it.
