### ISSUE TITLE
3.0.0-Beta2 bugs

### ISSUE THREAD

**Issue by s3thus** [evil-morfar/RCLootCouncil2#198]
Hi again :)
Once again thanks for your work put into this addon :) This time I've few non critical bugs:

1. when you have enabled to required note before submitting item response and items timeout without chosen response on item frame - frame is stuck open with `Timeout` written on it and (if print response is enabled) keeps spamming chat like this:
![image](https://user-images.githubusercontent.com/2890290/96708136-151bce80-1399-11eb-9903-aeb31ded26bb.png)

2. during our test session we had one occurrence of below bug - it happened when I was adding additional items to already running session - and we could not make it reproduced ever after:
```
1x AceLocale-3.0-6: RCLootCouncil: Missing entry for 'non_tradeable_reason_n_t'
[string "@RCLootCouncil\Modules\votingFrame.lua"]:1101: in function <RCLootCouncil\Modules\votingFrame.lua:1097>
```

3. When you add item to already running session last item is duplicated on item frame and given chance to be voted again but it's not duplicated on voting frame and responses chosen on item frame overwrite previous responses - I've made short video to show how it looks like (sorry for jumping screen I realized I've set recording fragment of screen and to follow mouse cursor): [video on streamable](https://streamable.com/2vm5b7)

**Comment by evil-morfar** [comment]
Thanks again.
1. I wonder if that has ever worked then - I haven't touched that for v3.0.
2. I believe this must have been someone using an older version, as I have no references to that in the code anymore.
3. I'll look into it.
