### ISSUE TITLE
Cant award item to a player using RC while default frame can.

### ISSUE THREAD

**Issue by SafeteeWoW** [evil-morfar/RCLootCouncil2#20]
During today's raid, I cant give item to a druid named "Fallenminos-Illidan".
It says
```
unable to give [itemlink] to feral -{player offline, left group  or instance?}
```
It seems the druid's name is wrongly recognized as "feral".
However, I can confirm that he's in the instance, and I can award him the item using the default Blizzard loot frame.

Reload does NOT fix the problem.
Problem happens too if I use the RCLootCouncil award button instead of RCLootCouncil-EPGP award button

**Comment by SafeteeWoW** [comment]
[RCLootCouncil.txt](https://github.com/evil-morfar/RCLootCouncil2/files/1393493/RCLootCouncil.txt)

**Comment by SafeteeWoW** [comment]
Checked the video I recorded, when I rightclicked on Fallenminos, the title of menu is correctly shown as "Fallenminos", but when I award the item using L["AWARD_FOR"],  the text of the following dialog is awarding to "feral" instead. This is so strange.

**Comment by SafeteeWoW** [comment]
Line 1182 of votingFrame.lua is bugged.

```
LibDialog:Spawn("RCLOOTCOUNCIL_CONFIRM_AWARD", RCVotingFrame:GetAwardPopupData(session, name, data, v))
```
```name``` should be ```candidateName```
This line is accessing the global variable ```name``` which is assigned to some strange value.

**Comment by SafeteeWoW** [comment]
Pull request to fix this:
https://github.com/evil-morfar/RCLootCouncil2/pull/21

**Comment by evil-morfar** [comment]
Merged your commit, thanks.
