### ISSUE TITLE
Bug: Council not being automatically assigned

### ISSUE THREAD

**Issue by jsmylnycky** [evil-morfar/RCLootCouncil2#202]
Version: 3.1.1

When I start the raid, I press "yes" on the popup to use RCLootCouncil.

Prior to the raid, I setup auto council by going to: Settings -> Master Looter -> Council tab.

In the "Guild Council Members" section, I select rank 4 (which is Council Alt, for our guild).

We end up getting some loot to drop, and the only member of the voting council actually assigned me is (the primary raid leader).

I end up fixing it by going back into Guild Council Members, changing the rank, hitting Okay, then going back and resetting it to Council Alt like I want.

This seems to have been an issue tonight (Dec 22) and at least last Wednesday (Dec 16), probably Tuesday (Dec 15) as well.

**Comment by evil-morfar** [comment]
Thanks for your report. It can indeed be delayed at the start of a raid, which will fix itself given enough time, or as you discovered by updating the council. Should be fixed next update.
