### ISSUE TITLE
 /RC List Command shows invalid timeframes

### ISSUE THREAD

**Issue by specialt123** [evil-morfar/RCLootCouncil2#205]
I have been ML for my guild since Wow Classic's release. I've noticed that when you award loot later and need to confirm the time left on items, the /rc list command provides highly inaccurate times. For example, they will show something like 8 hours 30 minutes instead of 1 hour 30 minutes remaining for the items. As far as I can tell, there isn't an area to set anything around a timezone to where it could possibly be misinterpreting this information. We are on Pacific Time for the West Coast of USA and that is the same time set on my in-game calendar. 

It would be nice to have the /rc list command show the actual time remaining on the item itself before it expires, but with it being off as much as it is, we are left to review all items in bag to confirm we're still good to progress in content.

**Comment by evil-morfar** [comment]
Should be fixed with latest version
