### ISSUE TITLE
Shard of Domination aren't ignored

### ISSUE THREAD

**Issue by ghost** [evil-morfar/RCLootCouncil2#210]
Hey,

I want to exclude [Shard of Domination](https://www.wowhead.com/items/gems/shard-of-domination#0-2+18) (not tradeable). I added all ID's to the ignore lists but there are still displayed in **History** window.

![image](https://user-images.githubusercontent.com/206181/124989903-f1d8a280-e03f-11eb-8e6a-aebcbd91fa6e.png)

![image](https://user-images.githubusercontent.com/206181/124989930-fd2bce00-e03f-11eb-8bf6-5097210ab7ec.png)

Thank you !

**Comment by evil-morfar** [comment]
Adding them to the ignore list only prevents them from being automatically added to a session in the future - it does NOT remove them from the history.

**Comment by Zazou89** [comment]
Hey, hum they were added before today's session.

**Comment by evil-morfar** [comment]
Just had a look at the code - adding them to the ignore list does indeed not prevent them from being added. It's actually intentional (as stated above), but I see where you're going, and make sure it'll be fixed.

**Comment by Zazou89** [comment]
Okay, perfect, thank you !
