### ISSUE TITLE
 /rc command conflicts with wow base ready check command,

### ISSUE THREAD

**Issue by Swordart25** [evil-morfar/RCLootCouncil2#215]
/rc command conflicts with wow base ready check command,
Can you add option to change keybind/command for showing it ?

**Comment by evil-morfar** [comment]
That's exactly what I created??

**Comment by Swordart25** [comment]
what do you mean?

**Comment by evil-morfar** [comment]
The referenced commit implemented what you wanted, and is included in the latest RCLootCouncil version. Just look for `Use /Rc` in RCLootCouncil > General Settings.
