### ISSUE TITLE
Question: Save votes for later awarding/pause a session

### ISSUE THREAD

**Issue by BreakBB** [evil-morfar/RCLootCouncil2#216]
Hey there,

our Raid just started using RCLootCouncil and we have yet to find the best workflow for us. A workflow we would love to implement, but can't seem to get working:

1. Loot Boss
2. Directly let all raid members respond on the dropped items
3. At some point later let the council vote on items and/or award them

The issue we have with this is, that we can only let raid members respond on items when we have a "session" running and we can't leave that session in the background. We would love to kill a few bosses, take their loot and then award some items on the run, based on the responses we get.

Is it possible to "pause" a session or something similar? Also it does not seem to be possible to start a session directly on the boss and then take the loot a PM to continue the raid.

**Comment by evil-morfar** [comment]
Assuming you're on retail I don't see why that wouldn't work. Why can't you "leave the session in the background"?

Also don't understand the last line. PM?

**Comment by evil-morfar** [comment]
You could also use award later and start the session after a few bosses/whenever you want. It doesnt take long for people to respond

**Comment by BreakBB** [comment]
Hey @evil-morfar thanks for the response on this. Since we found out that double clicking the header of the Voting Frame collapses it and there is also a way to rescale the frames with CRTL + mouse wheel, we have all that we need.

Thanks for this great addon 👍🏻
