### ISSUE TITLE
Patch 10.0 BugSacks

### ISSUE THREAD

**Issue by djodars89** [evil-morfar/RCLootCouncil2#220]
Unsure if this is the best way to share lua errors but here's my BugSacks related to RCLootCouncil:

[WoW10.0_RCLC_BugSacks.zip](https://github.com/evil-morfar/RCLootCouncil2/files/9880510/WoW10.0_RCLC_BugSacks.zip)

Thank you for your hard work!

**Comment by evil-morfar** [comment]
That's to be expected since the addon isn't updated for patch 10.0.4 yet.
Thanks anyways
