### ISSUE TITLE
/rc add all command (WotLK)

### ISSUE THREAD

**Issue by fgsfdss** [evil-morfar/RCLootCouncil2#221]
Sometimes, when attempting to use this command, I am not allowed to enter it in the chat. I spam return and it just stays in the edit box. All other chat messages and chat commands go through even despite errors, but this one doesn't go through at all.
I believe changing zone, relogging etc works, but that is not great during a boss fight. I unfortunately don't know what causes it.
Using latest Curseforge version, latest WotLK client.

**Comment by fgsfdss** [comment]
I'll try this next time I get the issue, but it is infrequent.

**Comment by evil-morfar** [comment]
You just have to run it once, and all future lua errors will show up

**Comment by fgsfdss** [comment]
Definitely, but also the ones for all my other addons; I wouldn't want to play with a permanent error screen until this issue arises again.

**Comment by fgsfdss** [comment]
Ok, I got the error again in today's raid, enabled the console command and got this:
```Message: ...dOns\RCLootCouncil_Classic\RCLootCouncil\ml_core.lua:100: attempt to get length of field 'lootTable' (a nil value)
Time: Sun Nov  6 18:54:09 2022
Count: 2
Stack: ...dOns\RCLootCouncil_Classic\RCLootCouncil\ml_core.lua:100: attempt to get length of field 'lootTable' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\ml_core.lua"]:100: in function `AddItem'
[string "@Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\ml_core.lua"]:345: in function `AddUserItem'
[string "@Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\core.lua"]:971: in function `ChatCmdAdd'
[string "@Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\core.lua"]:434: in function `?'
[string "@Interface\AddOns\ArkInventory\Externals\Ace3\AceConsole\AceConsole-3.0.lua"]:90: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:4933: in function <Interface\FrameXML\ChatFrame.lua:4879>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4596: in function <Interface\FrameXML\ChatFrame.lua:4595>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4632: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: ```

**Comment by fgsfdss** [comment]
Seems to be a conflict with ArkInventory, going by line 9?

**Comment by evil-morfar** [comment]
I don't think its an addon clash. The error indicates it's caused by attempting do ML stuff without the ML module being ready, i.e. haven't clicked "Yes" to the usage popup etc. I did add extra checks in recent versions that should prevent this, but it seems like it doesn't work. 

How often does this happen? Are you doing anything special when it happens (recent /reload, change loot method, etc)?

**Comment by fgsfdss** [comment]
We are always using group loot. I rarely get errors so I never really reload during raids.
We kill the boss(es), I wait until everybody has passed all items so I receive them, and then try to use the command.

Got the issue again today on both of my characters. It's always the first time that doesn't work, then I relog, and then it works for the rest of the raid. Same error each time, even across all three current tier instances.

**Comment by evil-morfar** [comment]
Odd. Think I need to have a look at your saved variables

**Comment by fgsfdss** [comment]
Sure. Can I privately send you those in a zip somehow?

**Comment by fgsfdss** [comment]
I also only just noticed that this is the wrong repo. Sorry about that. Should I create a copy issue in the correct one?

**Comment by evil-morfar** [comment]
It's probably easiest to send it on Discord.
No that's okay, you don't have to copy it.

**Comment by fgsfdss** [comment]
Sure, what's your Discord user name, and do you have any specific / public server I could join to have a mutual one? I am on all Classic class discords.

**Comment by evil-morfar** [comment]
Took it for granted you were on the RCLootCouncil Discord - https://discord.gg/WfYhCx9
