### ISSUE TITLE
Addon sometimes does not work correctly with no error

### ISSUE THREAD

**Issue by Lotan21** [evil-morfar/RCLootCouncil2#223]
After first time using the addon in Dragonflight raid I've encountered two issues, maybe related. Both happened in about half the loot sessions without any error popup.

1. Sometimes after receiving all the items that everyone have passed, the items are not added to the session automatically and I have to add them manually via /rc add. Other times it works correctly.
2. Sometimes using the trade UI a trade window with the correct recipient is opened but I get offer to add the proper item and have to find it and add move to the trade window manually. Other times it correctly adds the proper item automatically.

Can I somehow help to debug this when no errors are present?

**Comment by evil-morfar** [comment]
Send me your saved variable located at: `World of Warcraft\_retail_\WTF\Account\<YOUR ACCOUNT>\SavedVariables\RCLootCouncil.lua`

**Comment by Lotan21** [comment]
[RCLootCouncil.zip](https://github.com/evil-morfar/RCLootCouncil2/files/10239072/RCLootCouncil.zip)

**Comment by TranslatorPaul** [comment]
I have this same issue. Today and yesterday our first raid boss kill the addon worked perfectly. Everyone autopassed, loot auto added, and loot auto sent into trade windows. Then I don't know what went wrong after that, I had to manually add each item. And manually trade everything from my bag. 
[RCLootCouncil_translator.zip](https://github.com/evil-morfar/RCLootCouncil2/files/10240490/RCLootCouncil_translator.zip)

**Comment by evil-morfar** [comment]
Thanks for your reports, I think I've found the problem
