### ISSUE TITLE
Option to "not use RCLC" does not work when entering raid

### ISSUE THREAD

**Issue by Breakerzeus** [evil-morfar/RCLootCouncil2#224]
Hi,
We noticed that there seems to be an issue with the query, whether the user wants to use RCLC for the raid or not. We clicked "No" since we didn't want to use it until the last two bosses of the heroic raid. But still all our members had their loot automatically passed by RCLC. Our Raid Lead then disabled the addon, all of our roster reloaded the UI and we then had the need-greed dialogues from blizzard again.
So it seems that the option to not use RCLC is not working properly. Since there is no error or log I can't really provide any more information other than
- we clicked "no" when we were asked whether to use RCLC in raid or not
- loot still was automatically passed by all members by RCLC
- Workaround 1: RL disables addon and all members reload their UI
- Workaround 2: "never use RCLC" in the first place
- we play on Retail; EU

Since this happened twice by now and we had some struggle to collect and re-assign the loot manually, I thought it would be wise to report that isssue.
Also between the first "happening" and the last one, there were multiple versions we hoped to have fixed this. but they didn't.
ATM we run the latest version 3.6.4.

**Comment by evil-morfar** [comment]
Can you attach your saved variables? It's located at `../World of Warcraft/retail/WTF/Account/"account_name"/SavedVariables/RCLootCouncil.lua`

**Comment by evil-morfar** [comment]
Actually, found an issue with it. Will be fixed next update.
