### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ca0991** [evil-morfar/RCLootCouncil2#226]
The addon just auto passed on a clear item level upgrade. While doing Terros in the new raid the boss dropped 389 mail shoulders, my current shoulders sit at 376 ilvl. Wtihout notifying me in any way RC loot council auto passed on the item and it was won by someone else. I had to check loot in my chat box because I was so confused as I thought no loot had even dropped.

**Expected behavior**
Do not auto pass on loot that is a clear upgrade in a PUG raid.

**Error message**
None

[RCLootCouncil.zip](https://github.com/evil-morfar/RCLootCouncil2/files/10299943/RCLootCouncil.zip)

**Comment by ca0991** [comment]
I feel I should mention that this is my first time ever killing this boss on heroic.

**Comment by syndenbock** [comment]
This doesn't sound like a bug, the group lead just enabled the "handle group loot" option which causes you to automatically pass on everything so they can roll it out.

**Comment by evil-morfar** [comment]
Your saved variables shows you did the first boss on normal where it didn't do anything (although you did do a `/rc` before reloading). I expect you didn't reload before sending the file here, hence the heroic raid isn't included.

You can try to send it again, but it's probably overwritten by now.
