### ISSUE TITLE
[Feature] Require notes per response

### ISSUE THREAD

**Issue by evil-morfar** [evil-morfar/RCLootCouncil2#228]
Instead of a global require notes setting, move it into each response, allowing players to choose the exact response they want raiders to provide a note with.

### Mockup
(From Hunter#1239 on Discord)
![image](https://user-images.githubusercontent.com/10189576/210860248-01bfe714-2171-46a7-ac22-d91938ffcc0c.png)

**Comment by HunterHill317** [comment]
Just wanted to know if there was any potential update on this before the new raid?

**Comment by evil-morfar** [comment]
Most likely, yes
