### ISSUE TITLE
Cuztomizeable AnnounceItems

### ISSUE THREAD

**Issue by evil-morfar** [evil-morfar/RCLootCouncil2#23]
@SafeteeWoW  I made a quick implementation for your suggestion 7ce9f779a4535547ee285d356404ea226d98b962.

For now, I don't intent to make `db.announceItemString` editable in game in RCLootCouncil.
It's currently untested, but it should work as intended.

Let me know if that covers your need.

**Comment by SafeteeWoW** [comment]
It works. Just need some fixes.
1. ```message``` in line 602 should be messages.
2.  We should add an option for this.

**Comment by evil-morfar** [comment]
1. 41e07ad44345ce267836c196c857e9f2ecc6b804
2. I have nothing to add to it, so I don't see the need for it. Feel free to do so in EPGP though.

**Comment by SafeteeWoW** [comment]
I will make a PR for this.
With only &s and &p, there is no need.
But I plan to add "&l": The ivl and "&t": The type(trinket, mail chest, etc), then it will be very useful.

I don't think it makes sense to add this in EPGP.

**Comment by evil-morfar** [comment]
Handled in #27
