### ISSUE TITLE
[BUG] Unable to sync settings when on different (but connected) realms

### ISSUE THREAD

**Issue by Nuvelle** [evil-morfar/RCLootCouncil2#235]
Unable to sync settings when on different (but connected) realms.

I am on EU-Turalyon, someone else is on EU-Doomhammer. These are connected realms.

When we try to sync settings in either direction the sender goes to 100%, but the receiver is stuck on "Receiving data".

**To Reproduce**
1. Go to Synchronizer and select target on a different server. 
2. Have target ready to sync.
3. Click Sync. 
4. Accept incomming sync on remote user.
5. Wait & never be synced

**Expected behavior**
Sync to be possible cross server.

**Saved Variables**
unable to add .lua, will try after posted.

**Comment by Nuvelle** [comment]
[RCLootCouncil.txt](https://github.com/evil-morfar/RCLootCouncil2/files/11455083/RCLootCouncil.txt)
lua as .txt

**Comment by evil-morfar** [comment]
A very interesting problem indeed. Comms seems to be sending, but is never received. Going to take a while to figure out...

**Comment by evil-morfar** [comment]
This should be fixed with 3.10.5.
