### ISSUE TITLE
Autopass | Don't pass on transmoggable items

### ISSUE THREAD

**Issue by Urtgard** [evil-morfar/RCLootCouncil2#236]
I would like to have an extra option to not auto pass on items I could use for transmog. E.g. a warrior can learn bow appearances.
Actually this should be two options to distinct between source or appearance.

I could add this feature myself if you'll accept a pr for this.

**Comment by evil-morfar** [comment]
If you can create it, I'd be more than happy to include it. I'm not entirely sure how to determine whether a player can use a certain item for transmog or not
