### ISSUE TITLE
[BUG] LUA Error: bad argument #1 to 'strfind'

### ISSUE THREAD

**Issue by Enkaf** [evil-morfar/RCLootCouncil2#244]
Hello, 

Sometimes got lua error via addon !BugGrabber/BugSack:

54x ...dOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:101: bad argument #1 to 'strfind' (string expected, got nil)
Debugstack was nil.

No more. It happen in the city, not in raid/party.

**Comment by evil-morfar** [comment]
Was fixed with v3.9.3, but forgot to tag this issue. Thanks for the report.
