### ISSUE TITLE
[Feature] Autopass for weapons missing main stat

### ISSUE THREAD

**Issue by comp615** [evil-morfar/RCLootCouncil2#245]
**Description**
Would like to see an option alongside the other autopass options to allow me to auto-pass an item (weapon/trinket) when it is not compatible with my class. In particular, this could mean strength daggers if I'm a Mage for instance.

Happy to investigate implementation myself as I can code. Curious if there's any pitfalls to be aware of (i.e. old school xpacs where you actually could want off-stat stuff, or tmog)

**Comment by evil-morfar** [comment]
As far as I'm aware there's no such issue with trinkets. The current setup works by me running a piece of code to extract all trinkets from the dungeon journal and assign which specs can use them. Same should be possible for weapons (which is something I'd like to do), but the implementation is not clean, and I haven't found time to do so.

**Comment by evil-morfar** [comment]
Don't worry about pitfalls if you do try to do it :)

**Comment by evil-morfar** [comment]
Added in v3.11.0
