### ISSUE TITLE
[BUG] Additional buttons for chest slot of Amirdrassil raid armor not wroking

### ISSUE THREAD

**Issue by Sinnrg** [evil-morfar/RCLootCouncil2#246]
**Describe the bug**
Additional buttons (Chest) for Amirdrassil chest armor not working, shows default selection (Need, Greed, ...) buttons. For other chest armor, from older raids, works as intended. 

[RCLootCouncil.zip](https://github.com/evil-morfar/RCLootCouncil2/files/13413278/RCLootCouncil.zip)

**Comment by evil-morfar** [comment]
Your profile doesn't show you've changed said buttons. Remember to click the "okay" button after configuring the button names/responses.

**Comment by Sinnrg** [comment]
hm, i probably zipped before closing client didn't saved configuration. Also attaching screenshot.
[RCLootCouncil (2).zip](https://github.com/evil-morfar/RCLootCouncil2/files/13414377/RCLootCouncil.2.zip)
![Screenshot 2023-11-20 142019](https://github.com/evil-morfar/RCLootCouncil2/assets/151520223/1aff3f2f-4f9f-4991-9041-44f437455cc1)

**Comment by Sinnrg** [comment]
so was playing around debugging, found that those chest items assigned as INVTYPE_ROBE. had to manually copy INVTYPE_CHEST section and change to INVTYPE_ROBE in RCLootCouncil.lua and it worked out. Now need fix for addon to save it as INVTYPE_CHEST AND INVTYPE_ROBE

[RCLootCouncil (3).zip](https://github.com/evil-morfar/RCLootCouncil2/files/13440392/RCLootCouncil.3.zip)

**Comment by evil-morfar** [comment]
Hmm I remember dealing with that before, and thought it to be working. Will have to look into it again.
Nice find though

**Comment by evil-morfar** [comment]
Fixed in v3.10.4
