### ISSUE TITLE
[BUG] Issues after Amirdrassil cutscenes (following Smolderon, Tindral, Fyrakk). 

### ISSUE THREAD

**Issue by hfxRos** [evil-morfar/RCLootCouncil2#247]
My group has been having an issue where we are not getting any prompts for loot after killing an Amirdrassil boss which triggers a cutscene (Smolderon, Tindral, Fyrakk). All of the loot auto passes and goes to the master looter as expected, but no one gets any popups for items and there doesn't seem to be a way to manually start the process.

After killing a following boss, the loot for the previous boss which triggered the cutscene, as well at the boss just killed both pop up as if they were just killed.

We have tried doing this with two different people acting as master looter, both having the same issue. This is making doing loot after these 3 bosses very awkward.

**To Reproduce**
Defeat Smolderon, Tindral, or Fyrakk with an active RCLootCouncil session. Note that the addon does not prompt for loot after killing the boss and dismissing the cutscene. 

**Expected behavior**
The normal loot windows that would be expected after killing a boss with an active RCLootCouncil session active would appear after dismissing the cutscene.

[RCLootCouncil.zip](https://github.com/evil-morfar/RCLootCouncil2/files/13502995/RCLootCouncil.zip)

**Comment by evil-morfar** [comment]
Should be fixed with v3.10.2. Please report back if the issue persists.
