### ISSUE TITLE
Hidden window during looting[BUG]

### ISSUE THREAD

**Issue by phoenixoh7** [evil-morfar/RCLootCouncil2#248]
After loot is dropped in raid, the center of the screen has a hidden window that is preventing right-clicking. Multiple raiders experiencing it, only happens after RCLoot. Reloading does fix the issue

**Comment by Sacru** [comment]
Seconded, Thirded, Fourthed, Fifthed (at least from numerous raid members, including myself). 

Cannot interact with NPC's, have to turn your screen weird to right click anything. It's a _**massive hidden window**_ that takes up the middle 1/2 of the screen.
