### ISSUE TITLE
[BUG] Error Lua with Neat Minimap

### ISSUE THREAD

**Issue by blackjack1031** [evil-morfar/RCLootCouncil2#250]
This message pops up anytime i try to load in to the game. 
**Error message**
If you get an error message, please attach it.
Message: Interface/AddOns/NeatMinimap/NeatMinimap.lua:168: attempt to index field 'MinimapZoomOut' (a nil value)
Time: Mon Dec 18 10:21:05 2023
Count: 1
Stack: Interface/AddOns/NeatMinimap/NeatMinimap.lua:168: attempt to index field 'MinimapZoomOut' (a nil value)
[string "@Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua"]:152: in function <...dOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:150>
[string "=[C]"]: ?
[string "@Interface/AddOns/NeatMinimap/NeatMinimap.lua"]:168: in function `UpdateButtons'
[string "@Interface/AddOns/NeatMinimap/NeatMinimap.lua"]:217: in function `SetupMouseInOut'
[string "@Interface/AddOns/NeatMinimap/NeatMinimap.lua"]:272: in function <Interface/AddOns/NeatMinimap/NeatMinimap.lua:270>

Locals: private = <table> {
 ThrowError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:50
 DoesErrorExist = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:92
 ClearOldErrors = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:113
 SanitizeLine = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:88
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:122
 IncrementErrorCount = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:82
 NewError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:54
 IsRCLootCouncilError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:99
}
orig_errorhandler = <function> defined @Interface/SharedXML/SharedBasicControls.lua:360

**Saved Variables**
I almost always need your saved variables to investigate, so please attach it. It's located at `../World of Warcraft/retail/WTF/Account/"account_name"/SavedVariables/RCLootCouncil.lua`.

**Comment by blackjack1031** [comment]
Added rcloot council file.

**Comment by evil-morfar** [comment]
NeatMinimap is the cause of this, not RCLootCouncil.
