### ISSUE TITLE
[BUG]Lua Error when looking at reputations

### ISSUE THREAD

**Issue by blackjack1031** [evil-morfar/RCLootCouncil2#251]
Lua Error when looking at reputations. Every time i open up reputations and scroll down i am unable to go any further. 

Expect to be able to use my reputation window. Only time i can use it is when i disable rcloot council 

Message: Interface/FrameXML/ReputationFrame.lua:194: attempt to concatenate local 'standingID' (a nil value)
Time: Mon Dec 18 10:22:34 2023
Count: 1
Stack: Interface/FrameXML/ReputationFrame.lua:194: attempt to concatenate local 'standingID' (a nil value)
[string "@Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua"]:152: in function <...dOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:150>
[string "=[C]"]: ?
[string "@Interface/FrameXML/ReputationFrame.lua"]:194: in function `ReputationFrame_InitReputationRow'
[string "@Interface/FrameXML/ReputationFrame.lua"]:17: in function `initializer'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:382: in function `InvokeInitializer'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:391: in function `InvokeInitializers'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:718: in function <Interface/SharedXML/Scroll/ScrollBox.lua:696>
[string "=[C]"]: in function `Update'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:258: in function `SetScrollPercentageInternal'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:250: in function `SetScrollPercentage'
[string "@Interface/SharedXML/Scroll/ScrollController.lua"]:98: in function `ScrollInDirection'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:232: in function `ScrollInDirection'
[string "@Interface/SharedXML/Scroll/ScrollController.lua"]:89: in function <Interface/SharedXML/Scroll/ScrollController.lua:87>

Locals: private = <table> {
 ThrowError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:50
 DoesErrorExist = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:92
 ClearOldErrors = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:113
 SanitizeLine = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:88
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:122
 IncrementErrorCount = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:82
 NewError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:54
 IsRCLootCouncilError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:99
}
orig_errorhandler = <function> defined @Interface/SharedXML/SharedBasicControls.lua:360

**Comment by evil-morfar** [comment]
RCLootCouncil doesn't touch anything to do with reputation, and this is the first time of heard of such an issue (trust me, I'd be bombarded if RCLC did actually break it).
As to why it "only works with RCLC disabled" is hard to say - but I'd bet it works if RCLC is the only enabled addon. My guess is some other addon breaks it with some weird interaction with RCLC. Only way to find out is to disable addons until you find out which one.
