### ISSUE TITLE
NEED HELP: Raiders were able to roll on loot 

### ISSUE THREAD

**Issue by Vettic** [evil-morfar/RCLootCouncil2#256]
It was our first time using the addon, I performed a version check before pull and everyone was green/had the correct version installed. When we killed the boss, 4-5 players could still roll on the loot, and I didn't have the rclc dialogue to actually distribute loot.

**Comment by evil-morfar** [comment]
Were the in a different guild? Were you in a guild group?
If no to both, then I'd need your saved variables- it's located at: `../World of Warcraft/_retail_/WTF/Account/"account_name"/SavedVariables/RCLootCouncil.lua`.

**Comment by Vettic** [comment]
[RCLootCouncil.lua.txt](https://github.com/user-attachments/files/17018810/RCLootCouncil.lua.txt)
the loot event happens around 19:08. After it didn't work we turned it off for the rest of the run

**Comment by evil-morfar** [comment]
It seems like you had enabled "Always use RCLootCouncil with group loot" enabled before entering the raid. There's nothing wrong with that, but the combination of that and doing a /reload shortly after entering the raid made the addon not initialize properly afterwards. That would be a bug that I'm not sure why/how could happen, but I've added extra debug logs and checks for future version.

The short of it is, the addon will only handle loot if you've seen "RCLootCouncil: Now handles looting" in chat. If reloading (after being activated) it should print it again within 5 seconds - if it doesn't (bug) you can force it with `/rc start`.

This is what caused it to not need/greed on your end, and anyone that entered the raid or reloaded after your reload (assuming you were in a guild group). There might have been a few people auto passing if they entered the raid before you and didn't reload.

**Comment by Vettic** [comment]
Thanks, that makes sense, it seems it bugged out a bit more than that as I ran Vault of the Incarnates with a few guildies to figure out what went wrong, I had set RCLC to ask if it should run but i never got the prompt and never took loot master. When i set a guild mate as raid leader he got the prompt and took control, but giving me raid lead back did not give me the prompt. I removed RCLC and the user variables it saved and reinstalled and that seems to have fixed it.

**Comment by evil-morfar** [comment]
Not really, no. Without knowing exactly what happened (would need your SV for that), you probably didn't change the setting before entering the raid (or even the group). Giving lead to someone without it obviously worked - and so would deleting the SV (essentially resetting all options).

Doing a `/reload` or just `/rc start` as suggested would also have worked.
