### ISSUE TITLE
[Feature Request] Add "Tier Slot" to "Additional Buttons"

### ISSUE THREAD

**Issue by JuicyJuuce** [evil-morfar/RCLootCouncil2#257]
Currently the functionality I'm requesting can be achieved by adding additional buttons for each tier slot (head, shoulders, chest, hands, legs). This feature would allow you to add a set of buttons that would automatically apply to all five of those slots, saving you the trouble of having to do the same procedure five times and maintaining all five versions.

This feature is *partially* achieved currently with the "Armor Token" option, but this doesn't cover non-token gear drops that fit in tier slots that can be catalyzed into tier pieces.

**Comment by evil-morfar** [comment]
Sure - would probably just name it "Catalyst"
