### ISSUE TITLE
[BUG] - Voting windows player list freezes and breaks the scroll functionality in larger groups

### ISSUE THREAD

**Issue by JoelGeorge-Tech** [evil-morfar/RCLootCouncil2#261]
**Describe the bug**
As the master looter, the list of players and their selected options do not always remain loaded.
Sometimes the list will bug such that scrolling up and down the list does not reload the list with new entries as expected. The list will "freeze" say the bottom 16 rows in place and when scrolling, the top 4 entries will scroll as expected but the rest of the list remains frozen.

**To Reproduce**
Must be a large group in order to enable scrolling on the list
Does not always happen making this tricky to reproduce!
Happens most commonly towards the end of raid night with the last few bosses being the most problematic.
Have not tested in raids other than Nerubar Palace
Seems to persist through reload (even though the rclc session does not!)

**Expected behavior**
To consistently be able to scroll the list

**Error message**
No error message shown, no Lua error either.

**Saved Variables**

[SavedVariables.zip](https://github.com/user-attachments/files/17677173/SavedVariables.zip)

**Comment by evil-morfar** [comment]
Update the wowaudit addon and you should be fine.

**Comment by JoelGeorge-Tech** [comment]
Hey there.

I did as instructed and updated the add-on ahead of yesterdays raid however I was met with the same issue.

I have disabled many addons, particularly elvUI and am hopeful that come Wednesday I will be able to act as masterlooter without issue.

I will report back if the issue persists with an updated savedVariables.

**Comment by JoelGeorge-Tech** [comment]
Issue resolved. Thank you 🙏
