### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by SanUI** [evil-morfar/RCLootCouncil2#6]
You did not specify a license. It's common, but I like to be extra careful for those things.

So, can I fork this and whack away? I want to check out adding a module to it.

**Comment by evil-morfar** [comment]
Yeah sure, go ahead :)

**Comment by Eriner** [comment]
@evil-morfar If you have no preference, why not drop in a copy of the MIT license? From GitHub:

when you are on a repository home page, you can click on the `+` icon. To make the process easier, if you name the newly created file `LICENSE.md`, the license picker automatically appears.

**Comment by evil-morfar** [comment]
@Eriner I do have some preferences, I just really haven't thought too much about it. Thanks for the tip!
