### ISSUE TITLE
[Enhancement] Some sort of Pawn compatibility

### ISSUE THREAD

**Issue by itcotta** [evil-morfar/RCLootCouncil2#7]
Pawn basically is an addon that lets you see how good an upgrade is (in %) based on your stat weights, if there was a way to perhaps add some sort of pawn support so the loot master could see how good an item is for someone besides just ilvl that would be really useful.

**Comment by evil-morfar** [comment]
I use Pawn myself, so I'm very familiar with it, and it's definitely possible to add.

Currently a few things have been suggested to add to the voting frame:

- Pawn
- ilvl with decimals
- Number of upgraded/titanforged etc items
- Artifact information
- Number of setpieces

I've been debating with myself whether to add these to the core addon, or implement them as a downloadable module. I prefer the latter, as I imagine some (most?) prefer to keep it somewhat simple, and don't want the extra overhead these things creates.

Either way, I haven't worked much on this yet.

**Comment by evil-morfar** [comment]
Work have finally materialized, have a look at https://wow.curseforge.com/projects/rclootcouncil-extrautilities

**Comment by evil-morfar** [comment]
I still don't have a good way to track set pieces. Closing this for now.
