### ISSUE TITLE
Don't auto-pass relics for offspecs

### ISSUE THREAD

**Issue by xmyno** [evil-morfar/RCLootCouncil2#8]
Currently relics are auto-passed even if you could use it in one of your offspec weapons. I'm not sure if there is a better way than defining what each class can use. If there is not, maybe this saves you some research: https://github.com/mlsen/raidcomp/blob/master/frontend/app/scripts/misc/wow.js#L236 (created for a different project).

Also thanks, appreciate your hard work on this!

**Comment by evil-morfar** [comment]
I used the same approach in every other aspect of autopassing.
This will definitely make it a lot easier to implement, thanks a lot!

**Comment by evil-morfar** [comment]
Added in https://github.com/evil-morfar/RCLootCouncil2/commit/811384f48df0dbe5ef70c4bf5c84c39e65d4dfdc

**Comment by evil-morfar** [comment]
Just a heads up (not sure if it's relevant for you) but Blizzard classifies Storm relics as being of type "Wind".

**Comment by xmyno** [comment]
Why have consistent naming anyways.. Not important in my case, but still thanks!
