### ISSUE TITLE
Loot selection not popping up for some people

### ISSUE THREAD

**Issue by Niller2005** [evil-morfar/RCLootCouncil2#9]
http://pastebin.com/xYAkH8AY - the loot session
http://puu.sh/rA3VC/8e7db3b80e.jpg - how it looked

They have the lastest version, and so do the ML.

If you need anything else just tell me. :)

**Comment by evil-morfar** [comment]
I'd like to see the SavedVariables file from one of the affected people.

**Comment by Niller2005** [comment]
Sure, I'll get those tomorrow.

**Comment by Niller2005** [comment]
https://www.dropbox.com/s/v5bgpud3qzqov3p/RCLootCouncil.lua?dl=0

**Comment by evil-morfar** [comment]
Thanks.
Turns out you were running into the problem of Blizzard supplying "Unknown" as the name of the ML. I had added a check for that, but I forgot it would also contain realmname, so my `self.masterLooter == "Unknown"` didn't work. This is now fixed in 111efd928f9316c0cca9d6ccc32c206bd8f7f7fb.

**Comment by evil-morfar** [comment]
Also I expect that to be part of a release version either later today, or tomorrow.

**Comment by Niller2005** [comment]
Will it be out before monday evening? 👍

**Comment by evil-morfar** [comment]
Unfortunately I didn't have time for it during the weekend - I'll upload it today though.
